package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/go-pg/pg/v10/orm"
	"github.com/ulas96/luima"
	"github.com/ulas96/luima/examples/quickstart/graph/generated"
	"github.com/ulas96/luima/examples/quickstart/graph/model"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, personalID string, input model.UserInput) (*model.User, error) {
	return luima.Create(ctx, r.DB, newUser(personalID, input), "user "+personalID)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, personalID string, input model.UserInput) (*model.User, error) {
	return luima.Update(ctx, r.DB, newUser(personalID, input), "user "+personalID)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, personalID string) (bool, error) {
	return luima.Delete(ctx, r.DB, &model.User{PersonalID: personalID})
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	return luima.List[model.User](ctx, r.DB, func(q *orm.Query) *orm.Query {
		return q.Order("personal_id")
	})
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, personalID string) (*model.User, error) {
	return luima.Get(ctx, r.DB, &model.User{PersonalID: personalID})
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
