// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type UserInput struct {
	Name     string   `json:"name"`
	Company  string   `json:"company"`
	Projects []string `json:"projects"`
}
